# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c37b41dffc2380a003a43b4909e4ffbd0f347b9b4ed34f64e486d3c002cb79ee7689f528a7d6ce7522d06383d346160c530a1180c32e1e1757dedf9991b2a5

test:
  secret_key_base: e8650cc2e70ad0874c613aa5c37d4bcc94a673d542c30b3c3c1e2ab7a88dac15e07a1980f4abbb093f7e90905dea75acf501d43ba36cf4f817c6254c8108519e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
